<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="C:\Users\ADMIN\source\repos\software-design\Task1_Recursive_Factorial_Implementation\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="C:\Users\ADMIN\source\repos\software-design\Task1_Recursive_Factorial_Implementation\.editorconfig" />
  </ItemGroup>

</Project>
